# Generated by Django 2.0.3 on 2018-04-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlyFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date published')),
                ('route', models.CharField(default='', max_length=20)),
                ('mileage', models.FloatField(max_length=15)),
                ('oilwear', models.FloatField(max_length=15)),
                ('maintain', models.FloatField(max_length=3)),
                ('follow', models.FloatField(max_length=3)),
                ('work_days', models.IntegerField(default=0)),
                ('fix_days', models.IntegerField(default=0)),
                ('stop_days', models.IntegerField(default=0)),
                ('shunt_mailage', models.FloatField(max_length=15)),
                ('engage_mailage', models.FloatField(max_length=15)),
                ('public_mailage', models.FloatField(max_length=15)),
                ('fault_times', models.IntegerField(default=0)),
                ('fault_minutes', models.IntegerField(default=0)),
                ('carInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_info.BusInfo')),
            ],
        ),
    ]
