# Generated by Django 2.0.4 on 2018-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0003_monthlyfeedback_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='engage_mailage',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='follow',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='maintain',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='mileage',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='oilwear',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='public_mailage',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='shunt_mailage',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
