# Generated by Django 2.0.4 on 2018-04-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0004_auto_20180408_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMaintainCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(default='', max_length=10)),
                ('date', models.DateField()),
                ('num_fir_maintain', models.IntegerField(default=0)),
                ('num_sec_maintain', models.IntegerField(default=0)),
            ],
        ),
    ]
