# Generated by Django 2.0.4 on 2018-04-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0005_routemaintaincount'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfeedback',
            name='team_target',
            field=models.IntegerField(default=0),
        ),
    ]
