# Generated by Django 2.0.4 on 2018-04-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0006_monthlyfeedback_team_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='team_target',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
