# Generated by Django 2.0.4 on 2018-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0007_auto_20180411_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='fix_days',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='stop_days',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='work_days',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
