# Generated by Django 2.0.4 on 2018-04-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0008_auto_20180411_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='fault_minutes',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlyfeedback',
            name='fault_times',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
